"""Generate config/litellm.yaml from validated plans (M1-04).

- Protocol-specific LiteLLM model prefixes from verified upstream_protocol only
- Emits model_info.upstream_protocol / features / public_protocols
- Environment references only (os.environ/NAME) — never secret values
- Timestamped backup of previous litellm.yaml
- Atomic write: temp → validate → replace
- ASCII-safe output for Windows GBK locale open()
"""

from __future__ import annotations

import re
import shutil
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from shared_quota_router.config_schema import (
    ConfigValidationError,
    PlanConfig,
    PlanModelEntry,
    PlansDocument,
    load_plans_file,
    public_protocols_for,
)
from shared_quota_router.models import ApiProtocol, Feature

_SECRETISH_RE = re.compile(
    r"(?i)\b(sk-[a-zA-Z0-9]{10,}|ark-[a-zA-Z0-9]{8,}|Bearer\s+\S+)"
)


def ascii_safe(text: str) -> str:
    if not text:
        return ""
    out: list[str] = []
    for ch in text:
        code = ord(ch)
        if 32 <= code <= 126:
            out.append(ch)
        elif ch == "\t":
            out.append(" ")
        else:
            out.append("_")
    return "".join(out)


def litellm_model_for_protocol(protocol: ApiProtocol | None, model_name: str) -> str:
    """Map upstream protocol to LiteLLM model string.

    Never invent protocol from model name. Unknown/missing protocol uses a
    disabled openai/ placeholder only for inventory; generator marks enabled=false.
    """
    safe = ascii_safe(model_name)
    if protocol is ApiProtocol.ANTHROPIC_MESSAGES:
        return f"anthropic/{safe}"
    # Chat and Responses both use OpenAI-compatible provider adapters in v1.90.5
    return f"openai/{safe}"


def _feature_yaml_list(features: frozenset[Feature]) -> str:
    # Stable order for deterministic apply
    order = [Feature.TEXT, Feature.STREAMING, Feature.TOOLS, Feature.REASONING]
    items = [f.value for f in order if f in features]
    for f in sorted(features, key=lambda x: x.value):
        if f.value not in items:
            items.append(f.value)
    return "[" + ", ".join(items) + "]"


def _protocol_yaml_list(protocols: frozenset[ApiProtocol]) -> str:
    order = [
        ApiProtocol.OPENAI_CHAT,
        ApiProtocol.OPENAI_RESPONSES,
        ApiProtocol.ANTHROPIC_MESSAGES,
    ]
    items = [p.value for p in order if p in protocols]
    for p in sorted(protocols, key=lambda x: x.value):
        if p.value not in items:
            items.append(p.value)
    return "[" + ", ".join(items) + "]"


def _has_messages_to_chat_convert_policy(doc: PlansDocument) -> bool:
    """是否存在 logical：allow_conversion ∧ anthropic_messages→openai_chat（P1-SOT）。"""
    for lm in doc.logical_models.values():
        if not lm.allow_conversion:
            continue
        for src, tgt in lm.allowed_conversions:
            if (
                src is ApiProtocol.ANTHROPIC_MESSAGES
                and tgt is ApiProtocol.OPENAI_CHAT
            ):
                return True
    return False


def render_litellm_yaml(
    doc: PlansDocument, *, enable_messages_chat_native: bool = False
) -> str:
    """Render full litellm.yaml content (ASCII-safe).

    ``use_chat_completions_url_for_anthropic_messages`` 仅当
    ``enable_messages_chat_native`` ∧ 存在 Messages→Chat convert policy 时为 true。
    """
    lines: list[str] = [
        "# AUTO-GENERATED by shared_quota_router.generator - do not hand-edit model_list.",
        "# Source: config/plans.yaml | Secrets: .env only",
        "# Shared Quota strategy via LITELLM_WORKER_STARTUP_HOOKS bootstrap.",
        "# Protocol metadata: model_info.upstream_protocol / public_protocols (M1).",
        "",
        "model_list:",
    ]

    for plan in doc.plans:
        # 显式写出已校验的 quota_group_id；禁止 ascii_safe 静默改写（P1-QG-ID）。
        qg = plan.quota_group_id
        prio = plan.priority
        prov = ascii_safe(plan.provider_id)
        base_env = ascii_safe(plan.base_url_env)
        key_env = ascii_safe(plan.api_key_env)
        title = ascii_safe(plan.display_name) or ascii_safe(plan.id)
        lines.append("")
        lines.append(
            f"  # --- {title} (quota_group: {qg}, priority: {prio}) ---"
        )
        for model in plan.models:
            lines.extend(
                _render_deployment_block(
                    plan=plan,
                    model=model,
                    qg=qg,
                    prio=prio,
                    prov=prov,
                    base_env=base_env,
                    key_env=key_env,
                    doc=doc,
                )
            )

    lines.extend(
        [
            "",
            "router_settings:",
            "  routing_strategy: simple-shuffle",
            "  num_retries: 2",
            "  allowed_fails: 1",
            "  cooldown_time: 30",
            "  retry_after: 1",
            "",
            "general_settings:",
            "  master_key: os.environ/LITELLM_MASTER_KEY",
            "  # C1-05: cancel upstream LLM task on HTTP disconnect so streaming cleanup runs",
            "  cancel_on_disconnect: true",
            "",
            "litellm_settings:",
            "  callbacks:",
            "    - shared_quota_callback.callback_instance",
            "  # M3-04: do not silently drop tools/stream params; gates reject first",
            "  drop_params: false",
            "  # G0-Native: Messages + openai/ -> chat completions URL (not Responses API).",
            "  # P1-SOT: true only when CLI --enable-messages-chat-native AND convert policy.",
            "  # Staging conversion still needs PROTOCOL_* flags. Env is not production SoT.",
            (
                "  use_chat_completions_url_for_anthropic_messages: "
                + (
                    "true"
                    if (
                        enable_messages_chat_native
                        and _has_messages_to_chat_convert_policy(doc)
                    )
                    else "false"
                )
            ),
            "",
        ]
    )
    # P1-02: emit logical-model policy for runtime conversion allowlists
    lines.extend(_render_logical_models_section(doc))
    text = "\n".join(lines)
    # Final secret scan on output
    if _SECRETISH_RE.search(text):
        raise ConfigValidationError(
            "generated litellm.yaml would contain secret-like material; aborting"
        )
    # Ensure pure ASCII
    text.encode("ascii")
    return text


def _render_logical_models_section(doc: PlansDocument) -> list[str]:
    """Emit ``shared_quota_logical_models`` for runtime policy reload (P1-02)."""
    if not doc.logical_models:
        return []
    lines = [
        "# Runtime policy (ignored by LiteLLM core; consumed by shared_quota_router)",
        "shared_quota_logical_models:",
    ]
    for mg in sorted(doc.logical_models.keys()):
        lm = doc.logical_models[mg]
        lines.append(f"  {ascii_safe(mg)}:")
        pubs = sorted(p.value for p in lm.public_protocols)
        lines.append(f"    public_protocols: [{', '.join(pubs)}]")
        lines.append(
            f"    allow_conversion: {'true' if lm.allow_conversion else 'false'}"
        )
        if lm.allowed_conversions:
            lines.append("    conversion_policy:")
            lines.append("      allowed:")
            for src, tgt in sorted(
                lm.allowed_conversions, key=lambda x: (x[0].value, x[1].value)
            ):
                lines.append(f"        - from: {src.value}")
                lines.append(f"          to: {tgt.value}")
        if lm.advertised_features:
            lines.append(
                f"    advertised_features: {_feature_yaml_list(lm.advertised_features)}"
            )
        if lm.compose is not None:
            lines.append("    compose:")
            lines.append(f"      template: {ascii_safe(lm.compose.template)}")
            lines.append(f"      execute_model: {ascii_safe(lm.compose.execute_model)}")
            lines.append(
                f"      translate_model: {ascii_safe(lm.compose.translate_model)}"
            )
    lines.append("")
    return lines


def _render_deployment_block(
    *,
    plan: PlanConfig,
    model: PlanModelEntry,
    qg: str,
    prio: int,
    prov: str,
    base_env: str,
    key_env: str,
    doc: PlansDocument,
) -> list[str]:
    model_name = ascii_safe(model.model)
    # deployment_id = {plan.id}-{model}；与 quota_group_id 解耦（同 qg 可有多 plan）。
    dep_id = re.sub(r"[^a-zA-Z0-9._-]", "-", f"{plan.id}-{model_name}")
    proto = plan.resolved_protocol(model)
    features = plan.resolved_features(model)
    streaming = plan.resolved_streaming(model)
    enabled = plan.resolved_enabled(model)
    # Unknown / missing protocol ⇒ disabled deployment (not rejected if plan allowed)
    if proto is None:
        enabled = False
    public = public_protocols_for(doc, model.model)
    lm = doc.logical_models.get(model.model)
    upstream_name = model_name
    if lm is not None and lm.compose is not None and lm.compose.execute_model:
        upstream_name = ascii_safe(lm.compose.execute_model)
    litellm_model = litellm_model_for_protocol(proto, upstream_name)

    block = [
        f"  - model_name: {model_name}",
        "    model_info:",
        f"      deployment_id: {dep_id}",
        f"      provider_id: {prov}",
        f"      account_id: {qg}",
        f"      quota_group_id: {qg}",
        f"      priority: {prio}",
        f"      enabled: {'true' if enabled else 'false'}",
    ]
    if proto is not None:
        block.append(f"      upstream_protocol: {proto.value}")
    if features:
        block.append(f"      supported_features: {_feature_yaml_list(features)}")
    block.append(f"      supports_streaming: {'true' if streaming else 'false'}")
    timeout = 300
    if lm is not None and lm.compose is not None:
        tmpl = (lm.compose.template or "vision").strip() or "vision"
        if tmpl == "vision":
            timeout = max(timeout, 480)
    if public:
        block.append(f"      public_protocols: {_protocol_yaml_list(public)}")
    if lm is not None and lm.advertised_features:
        block.append(
            f"      advertised_features: {_feature_yaml_list(lm.advertised_features)}"
        )
    if model.facade_role:
        block.append(f"      facade_role: {model.facade_role}")
    if lm is not None and lm.compose is not None:
        block.append("      compose:")
        block.append(f"        template: {ascii_safe(lm.compose.template)}")
        block.append(f"        execute_model: {ascii_safe(lm.compose.execute_model)}")
        block.append(
            f"        translate_model: {ascii_safe(lm.compose.translate_model)}"
        )
    conversions = plan.resolved_conversions(model)
    if conversions:
        block.append("      conversions:")
        for cap in conversions:
            block.append(f"        - from: {cap.source.value}")
            block.append(f"          to: {cap.target.value}")
            block.append(f"          fidelity: {cap.fidelity.value}")
            block.append("          streaming: false")
            req = sorted(f.value for f in cap.request_features)
            resp = sorted(f.value for f in cap.response_features)
            block.append("          features:")
            block.append(f"            request: [{', '.join(req)}]")
            block.append(f"            response: [{', '.join(resp)}]")
    block.extend(
        [
            "    litellm_params:",
            f"      model: {litellm_model}",
            f"      api_base: os.environ/{base_env}",
            f"      api_key: os.environ/{key_env}",
            f"      timeout: {timeout}",
        ]
    )
    # Responses 公网 + Chat 上游：强制走 chat completions bridge
    if (
        proto is ApiProtocol.OPENAI_CHAT
        and lm is not None
        and ApiProtocol.OPENAI_RESPONSES in lm.public_protocols
    ):
        block.append("      use_chat_completions_api: true")
    block.append("")
    return block

def validate_generated_yaml_text(text: str) -> None:
    """Lightweight post-generation checks before replace."""
    if not text.strip().startswith("# AUTO-GENERATED"):
        raise ConfigValidationError("generated content missing AUTO-GENERATED header")
    if "model_list:" not in text:
        raise ConfigValidationError("generated content missing model_list")
    if "os.environ/" not in text:
        raise ConfigValidationError("generated content missing env references")
    # No inline secret values
    if _SECRETISH_RE.search(text):
        raise ConfigValidationError("generated content contains secret-like strings")
    # Must not embed raw env file style KEY=value secrets
    for line in text.splitlines():
        if re.search(r"api_key:\s*['\"]?(sk-|ark-)", line, re.I):
            raise ConfigValidationError("generated api_key must be os.environ/ reference")
    text.encode("ascii")


def write_litellm_yaml_atomic(
    content: str,
    output_path: str | Path,
    *,
    backup_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Validate, backup existing file, write via temp + replace.

    On validation failure the previous file is left untouched.
    """
    output = Path(output_path)
    validate_generated_yaml_text(content)

    backup_path: Path | None = None
    if output.is_file():
        bdir = Path(backup_dir) if backup_dir else output.parent / "backups"
        bdir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        backup_path = bdir / f"litellm.yaml.{stamp}.bak"
        shutil.copy2(output, backup_path)

    output.parent.mkdir(parents=True, exist_ok=True)
    # Write temp in same directory for atomic replace on Windows
    fd, tmp_name = tempfile.mkstemp(
        prefix="litellm.",
        suffix=".yaml.tmp",
        dir=str(output.parent),
    )
    tmp_path = Path(tmp_name)
    try:
        with open(fd, "w", encoding="ascii", newline="\n") as fh:
            fh.write(content)
            if not content.endswith("\n"):
                fh.write("\n")
        # Re-validate temp file bytes
        raw = tmp_path.read_bytes()
        raw.decode("ascii")
        if _SECRETISH_RE.search(raw.decode("ascii")):
            raise ConfigValidationError("temp file failed secret scan")
        # Atomic replace
        tmp_path.replace(output)
    except Exception:
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)
        raise

    return {
        "output": str(output),
        "backup": str(backup_path) if backup_path else None,
        "bytes": output.stat().st_size,
    }


def apply_plans_to_litellm(
    plans_path: str | Path,
    output_path: str | Path,
    *,
    backup_dir: str | Path | None = None,
    enable_messages_chat_native: bool = False,
) -> dict[str, Any]:
    """Load → validate → render → atomic write. Fail-closed on any error."""
    doc = load_plans_file(plans_path)
    content = render_litellm_yaml(
        doc, enable_messages_chat_native=enable_messages_chat_native
    )
    meta = write_litellm_yaml_atomic(content, output_path, backup_dir=backup_dir)
    meta["plans"] = len(doc.plans)
    meta["logical_models"] = len(doc.logical_models)
    meta["deployments"] = sum(len(p.models) for p in doc.plans)
    meta["enable_messages_chat_native"] = bool(enable_messages_chat_native)
    return meta
